# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              wazza is awesome
email:              'warren /at/ bainsworld.com'
author:             Warren Bain
description: >
  A vainglorious attempt to prove Wazza's general awesomeness.
  Then again, people have actually rated him for that on LinkedIn.
baseurl:            ''
url:                'http://wazza-is-awesome.com'
twitter_username:   thoughtcroft
github_username:    thoughtcroft
linkedin_username:  warrenbain

# Build settings
permalink:          none
markdown:           kramdown
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - _gists

# Custom require for plugins if not the name of the gem
# (otherwise just add to Gemfile)
gems:

# Pagination
paginate:           7
paginate_path:      'page/:num'

# RSS Feed
max_rss_posts:      10

# Tags
tag_page_layout:    tag-page
tag_page_dir:       tag
max_related_posts:  4

# Disqus
disqus_id:          'wazza-is-awesome'

# Google
google_analytics:   'UA-81713354-1'

# Gist
gist:
  noscript:         false
