# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wazza is awesome
email: warren@thoughtcroft.com
author: Warren Bain
description: > # this means to ignore newlines until "baseurl:"
  Warren Bain's vainglorious attempt to prove his general awesomeness.
  Then again, people actually rated him for that on LinkedIn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wazza-is-awesome.com" # the base hostname & protocol for your site
twitter_username: thoughtcroft
github_username: thoughtcroft
linkedin_username: warrenbain

# Build settings
markdown: kramdown
